name: release
on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: 'pages'
    cancel-in-progress: false

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            # Step 1: Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v2

            # Step 2: Zip the "public" directory
            - name: Zip public directory
              uses: vimtor/action-zip@v1.2
              with:
                  files: public/
                  dest: public.zip

            # Step 3: Create a GitHub release
            - name: Create GitHub release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: Release ${{ github.ref_name }}
                  body: |
                      Changes in this release:
                      - Added zipped "public" directory.
                  draft: false
                  prerelease: false

            # Step 4: Upload the zipped file as a release asset
            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create-release.outputs.upload_url }}
                  asset_path: ./public.zip
                  asset_name: public.zip
                  asset_content_type: application/zip
